### ISSUE TITLE
Undiagnosed crash 2013-12-10

### ISSUE THREAD

**Issue by epochwolf** [epochwolf/pious-plum#15]
From the console:

```
erichmenge => #RubyonRails-offtopic: https://goo.gl/maps/S0u9m
{ url: 'https://goo.gl/maps/S0u9m',
  protocol: 'https',
  host: 'goo.gl',
  port: '443',
  path: '/maps/S0u9m',
  query: undefined }
https

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parse Error
    at CleartextStream.socketOnData (http.js:1564:20)
    at CleartextStream.read [as _read] (tls.js:502:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:219:10)
    at writeOrBuffer (_stream_writable.js:209:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:573:24)
    at flow (_stream_readable.js:582:7)
    at Socket.pipeOnReadable (_stream_readable.js:614:5)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
```

**Comment by epochwolf** [comment]
Similar crash: 

    ddd => #RubyonRails-offtopic: !code
    helpa => #RubyonRails-offtopic: We cannot help you with your problem if you don't show us your code. Please put it on http://gist.github.com and give us the URL so we can see it.
    I see: http://gist.github.com/
    { protocol: 'http:',
      slashes: true,
      auth: null,
      host: 'gist.github.com',
      port: null,
      hostname: 'gist.github.com',
      hash: null,
      search: null,
      query: null,
      pathname: '/',
      path: '/',
      href: 'http://gist.github.com/' }
    http

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: Parse Error
        at CleartextStream.socketOnData (http.js:1583:20)
        at CleartextStream.read [as _read] (tls.js:511:12)
        at CleartextStream.Readable.read (_stream_readable.js:320:10)
        at EncryptedStream.write [as _write] (tls.js:366:25)
        at doWrite (_stream_writable.js:223:10)
        at writeOrBuffer (_stream_writable.js:213:5)
        at EncryptedStream.Writable.write (_stream_writable.js:180:11)
        at write (_stream_readable.js:583:24)
        at flow (_stream_readable.js:592:7)
        at Socket.pipeOnReadable (_stream_readable.js:624:5)
        at Socket.EventEmitter.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:408:10)

**Comment by mvndaai** [comment]
Just and FYI. I was able to fix a similar error by adding an .on("error"..) to my http request.

<pre>
http.request(post, function(response) {
    ...
}).on("error", function(e){
    console.log("Got error: " + e.message);
});
</pre>
